### ISSUE TITLE
MIDI_JINGLE packet does not work on the JavaScript client.

### ISSUE THREAD

**Issue by ultraviolet-jordan** [2004scape/Server#113]
Works fine on the Java client.

Only quest reward screen is using this atm.

**Comment by Pazaz** [comment]
I'm going to rename the midi_jingle variables for clarity, my bad. `delay` isn't the time to start the jingle, it's the time to continue the music it replaced. If you send 0 it won't continue music tracks, and the webclient is set to loop midis so that's why it sounds strange.

`midi_jingle("quest complete <tostring($random)>", 0);`
$delay (time to end/time to next track) is in ms (unique per jingle), but it isn't like you open VLC and get the length of the track since there can be empty notes or properties their synthesizer doesn't understand. `quest complete 2` should be like 7000. The Java client will play empty noise, the JavaScript client may restart the track instead of empty noise.

So I'll look into the looping difference, but you should send a time here. There also may be a bug with restarting the music twice after resuming, checking that out too
